package com.web.pet.pojo.annotations;

// Generated 26/01/2013 09:01:06 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Cotservicio generated by hbm2java
 */
@Entity
@Table(name = "cotservicio")
public class Cotservicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2773494360546114961L;
	private int idservicio;
	private Setestado setestado;
	private Setusuario setusuario;
	private Cottiposervicio cottiposervicio;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
	private BigDecimal valor;
//	private Set<Petordenserviciodetalle> petordenserviciodetalles = new HashSet<Petordenserviciodetalle>(0);
//	private Set<Petcomisiondetalle> petcomisiondetalles = new HashSet<Petcomisiondetalle>(0);

	public Cotservicio() {
	}

	public Cotservicio(int idservicio, String nombre, Date fecharegistro) {
		this.idservicio = idservicio;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
	}

	public Cotservicio(int idservicio, Setestado setestado,
			Setusuario setusuario, Cottiposervicio cottiposervicio,
			String nombre, String descripcion, Date fecharegistro,
			String iplog, BigDecimal valor/*, Set<Petordenserviciodetalle> petordenserviciodetalles,
			Set<Petcomisiondetalle> petcomisiondetalles*/) {
		this.idservicio = idservicio;
		this.setestado = setestado;
		this.setusuario = setusuario;
		this.cottiposervicio = cottiposervicio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.valor = valor;
//		this.petordenserviciodetalles = petordenserviciodetalles;
//		this.petcomisiondetalles = petcomisiondetalles;
	}

	@Id
	@Column(name = "idservicio", unique = true, nullable = false)
	public int getIdservicio() {
		return this.idservicio;
	}

	public void setIdservicio(int idservicio) {
		this.idservicio = idservicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtiposervicio")
	public Cottiposervicio getCottiposervicio() {
		return this.cottiposervicio;
	}

	public void setCottiposervicio(Cottiposervicio cottiposervicio) {
		this.cottiposervicio = cottiposervicio;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}
	
	@Column(name = "valor", precision = 5)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotservicio", targetEntity = Petordenserviciodetalle.class)
	public Set<Petordenserviciodetalle> getPetordenserviciodetalles() {
		return this.petordenserviciodetalles;
	}

	public void setPetordenserviciodetalles(Set<Petordenserviciodetalle> petordenserviciodetalles) {
		this.petordenserviciodetalles = petordenserviciodetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cotservicio", targetEntity = Petcomisiondetalle.class)
	public Set<Petcomisiondetalle> getPetcomisiondetalles() {
		return this.petcomisiondetalles;
	}

	public void setPetcomisiondetalles(Set<Petcomisiondetalle> petcomisiondetalles) {
		this.petcomisiondetalles = petcomisiondetalles;
	}
*/
}
