package com.web.pet.pojo.annotations;

// Generated 29/01/2013 08:42:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PetcomisiondetalleId generated by hbm2java
 */
@Embeddable
public class PetcomisiondetalleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7317355792233935893L;
	private int idcomision;
	private int idcomisiondetalle;

	public PetcomisiondetalleId() {
	}

	public PetcomisiondetalleId(int idcomision, int idcomisiondetalle) {
		this.idcomision = idcomision;
		this.idcomisiondetalle = idcomisiondetalle;
	}

	@Column(name = "idcomision", nullable = false)
	public int getIdcomision() {
		return this.idcomision;
	}

	public void setIdcomision(int idcomision) {
		this.idcomision = idcomision;
	}

	@Column(name = "idcomisiondetalle", nullable = false)
	public int getIdcomisiondetalle() {
		return this.idcomisiondetalle;
	}

	public void setIdcomisiondetalle(int idcomisiondetalle) {
		this.idcomisiondetalle = idcomisiondetalle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PetcomisiondetalleId))
			return false;
		PetcomisiondetalleId castOther = (PetcomisiondetalleId) other;

		return (this.getIdcomision() == castOther.getIdcomision())
				&& (this.getIdcomisiondetalle() == castOther
						.getIdcomisiondetalle());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcomision();
		result = 37 * result + this.getIdcomisiondetalle();
		return result;
	}

}
