package com.web.pet.pojo.annotations;

// Generated 29/01/2013 08:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petcomision generated by hbm2java
 */
@Entity
@Table(name = "petcomision")
public class Petcomision implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9071281121928649519L;
	private int idcomision;
	private Petestado petestado;
	private Setusuario setusuario;
	private Cotpersona cotpersona;
	private Date fecharegistro;
	private String iplog;
//	private Set<Petcomisiondetalle> petcomisiondetalles = new HashSet<Petcomisiondetalle>(0);

	public Petcomision() {
	}

	public Petcomision(int idcomision, Cotpersona cotpersona, Date fecharegistro) {
		this.idcomision = idcomision;
		this.cotpersona = cotpersona;
		this.fecharegistro = fecharegistro;
	}

	public Petcomision(int idcomision, Petestado petestado,
			Setusuario setusuario, Cotpersona cotpersona, Date fecharegistro,
			String iplog/*, Set<Petcomisiondetalle> petcomisiondetalles*/) {
		this.idcomision = idcomision;
		this.petestado = petestado;
		this.setusuario = setusuario;
		this.cotpersona = cotpersona;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
//		this.petcomisiondetalles = petcomisiondetalles;
	}

	@Id
	@Column(name = "idcomision", unique = true, nullable = false)
	public int getIdcomision() {
		return this.idcomision;
	}

	public void setIdcomision(int idcomision) {
		this.idcomision = idcomision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Petestado getPetestado() {
		return this.petestado;
	}

	public void setPetestado(Petestado petestado) {
		this.petestado = petestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Cotpersona getCotpersona() {
		return this.cotpersona;
	}

	public void setCotpersona(Cotpersona cotpersona) {
		this.cotpersona = cotpersona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petcomision", targetEntity = Petcomisiondetalle.class)
	public Set<Petcomisiondetalle> getPetcomisiondetalles() {
		return this.petcomisiondetalles;
	}

	public void setPetcomisiondetalles(Set<Petcomisiondetalle> petcomisiondetalles) {
		this.petcomisiondetalles = petcomisiondetalles;
	}
*/
}
