package com.web.pet.pojo.annotations;

// Generated 26/07/2012 03:22:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petespecie generated by hbm2java
 */
@Entity
@Table(name = "petespecie", schema = "pets")
public class Petespecie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1265654006613027492L;
	private int idespecie;
	private Petestado petestado;
	private Setusuario setusuario;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
//	private Set<Petmascota> petmascotas = new HashSet<Petmascota>(0);

	public Petespecie() {
	}

	public Petespecie(int idespecie, String nombre, Date fecharegistro) {
		this.idespecie = idespecie;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
	}

	public Petespecie(int idespecie, Petestado petestado,
			Setusuario setusuario, String nombre, String descripcion,
			Date fecharegistro, String iplog/*, Set<Petmascota> petmascotas*/) {
		this.idespecie = idespecie;
		this.petestado = petestado;
		this.setusuario = setusuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
//		this.petmascotas = petmascotas;
	}

	@Id
	@Column(name = "idespecie", unique = true, nullable = false)
	public int getIdespecie() {
		return this.idespecie;
	}

	public void setIdespecie(int idespecie) {
		this.idespecie = idespecie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Petestado getPetestado() {
		return this.petestado;
	}

	public void setPetestado(Petestado petestado) {
		this.petestado = petestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petespecie", targetEntity = Petmascota.class)
	public Set<Petmascota> getPetmascotas() {
		return this.petmascotas;
	}

	public void setPetmascotas(Set<Petmascota> petmascotas) {
		this.petmascotas = petmascotas;
	}
*/
}
