package com.web.pet.pojo.annotations;

// Generated 26/07/2012 03:22:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petmascotacolor generated by hbm2java
 */
@Entity
@Table(name = "petmascotacolor", schema = "pets")
public class Petmascotacolor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7967921817126534849L;
	private int idmascotacolor;
	private Petmascota petmascota;
	private Petestado petestado;
	private Cotcolor cotcolor;
	private Setusuario setusuario;
	private Date fecharegistro;
	private String iplog;

	public Petmascotacolor() {
	}

	public Petmascotacolor(int idmascotacolor, Petmascota petmascota,
			Cotcolor cotcolor, Date fecharegistro) {
		this.idmascotacolor = idmascotacolor;
		this.petmascota = petmascota;
		this.cotcolor = cotcolor;
		this.fecharegistro = fecharegistro;
	}

	public Petmascotacolor(int idmascotacolor, Petmascota petmascota,
			Petestado petestado, Cotcolor cotcolor, Setusuario setusuario,
			Date fecharegistro, String iplog) {
		this.idmascotacolor = idmascotacolor;
		this.petmascota = petmascota;
		this.petestado = petestado;
		this.cotcolor = cotcolor;
		this.setusuario = setusuario;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idmascotacolor", unique = true, nullable = false)
	public int getIdmascotacolor() {
		return this.idmascotacolor;
	}

	public void setIdmascotacolor(int idmascotacolor) {
		this.idmascotacolor = idmascotacolor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmascota", nullable = false)
	public Petmascota getPetmascota() {
		return this.petmascota;
	}

	public void setPetmascota(Petmascota petmascota) {
		this.petmascota = petmascota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Petestado getPetestado() {
		return this.petestado;
	}

	public void setPetestado(Petestado petestado) {
		this.petestado = petestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcolor", nullable = false)
	public Cotcolor getCotcolor() {
		return this.cotcolor;
	}

	public void setCotcolor(Cotcolor cotcolor) {
		this.cotcolor = cotcolor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
