package com.web.pet.pojo.annotations;

// Generated 26/07/2012 03:22:37 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Petmascota generated by hbm2java
 */
@Entity
@Table(name = "petmascota")
public class Petmascota implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6716243937856807942L;
	private int idmascota;
	private Petestado petestado;
	private Cottipoidentificacion cottipoidentificacion;
	private Petraza petraza;
	private Setusuario setusuario;
	private Petespecie petespecie;
	private Cotpersona cotpersona;
	private String nombre;
	private Date fecharegistro;
	private String iplog;
	private Integer sexo;
	private BigDecimal pesokg;
	private Date fechanacimiento;
	private String caracteristicas;
	private boolean pedigree;
	private boolean microchip;
	private String numeroidentificacion;
	private Date fechafallecimiento;
//	private Set<Petcomisiondetalle> petcomisiondetalles = new HashSet<Petcomisiondetalle>(0);
//	private Set<Petordenservicio> petordenservicios = new HashSet<Petordenservicio>(0);
//	private Set<Object> pethistoriaclinicas = new HashSet<Object>(0);
	private Set<Petmascotacolor> petmascotacolors = new HashSet<Petmascotacolor>(0);
//	private Set<Object> cotdocumentos = new HashSet<Object>(0);
//	private Set<Petfoto> petfotos = new HashSet<Petfoto>(0);
//	private Set<Petsolicitudmortuoria> petsolicitudmortuorias = new HashSet<Petsolicitudmortuoria>(0);

	public Petmascota() {
	}

	public Petmascota(int idmascota, Petraza petraza, Petespecie petespecie,
			Cotpersona cotpersona, String nombre, Date fecharegistro) {
		this.idmascota = idmascota;
		this.petraza = petraza;
		this.petespecie = petespecie;
		this.cotpersona = cotpersona;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
	}

	public Petmascota(int idmascota, Petestado petestado, 
			Cottipoidentificacion cottipoidentificacion, Petraza petraza,
			Setusuario setusuario, Petespecie petespecie,
			Cotpersona cotpersona, String nombre, Date fecharegistro,
			String iplog, Integer sexo, BigDecimal pesokg,
			Date fechanacimiento, String caracteristicas,
			String numeroidentificacion, boolean pedigree, boolean microchip, Date fechafallecimiento/*, 
			Set<Object> pethistoriaclinicas, Set<Petmascotacolor> petmascotacolors, Set<Object> cotdocumentos,
			Set<Petfoto> petfotos,
			Set<Petcomisiondetalle> petcomisiondetalles, Set<Petordenservicio> petordenservicios, Set<Petsolicitudmortuoria> petsolicitudmortuorias*/) {
		this.idmascota = idmascota;
		this.petestado = petestado;
		this.cottipoidentificacion = cottipoidentificacion;
		this.petraza = petraza;
		this.setusuario = setusuario;
		this.petespecie = petespecie;
		this.cotpersona = cotpersona;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.sexo = sexo;
		this.pesokg = pesokg;
		this.fechanacimiento = fechanacimiento;
		this.caracteristicas = caracteristicas;
		this.numeroidentificacion = numeroidentificacion;
		this.pedigree = pedigree;
		this.microchip = microchip;
//		this.pethistoriaclinicas = pethistoriaclinicas;
//		this.petmascotacolors = petmascotacolors;
//		this.cotdocumentos = cotdocumentos;
//		this.petfotos = petfotos;
		this.fechafallecimiento = fechafallecimiento;
//		this.petcomisiondetalles = petcomisiondetalles;
//		this.petordenservicios = petordenservicios;
//		this.petsolicitudmortuorias = petsolicitudmortuorias;
	}

	@Id
	@Column(name = "idmascota", unique = true, nullable = false)
	public int getIdmascota() {
		return this.idmascota;
	}

	public void setIdmascota(int idmascota) {
		this.idmascota = idmascota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Petestado getPetestado() {
		return this.petestado;
	}

	public void setPetestado(Petestado petestado) {
		this.petestado = petestado;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipoidentificacion")
	public Cottipoidentificacion getCottipoidentificacion() {
		return this.cottipoidentificacion;
	}

	public void setCottipoidentificacion(
			Cottipoidentificacion cottipoidentificacion) {
		this.cottipoidentificacion = cottipoidentificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idraza", nullable = false)
	public Petraza getPetraza() {
		return this.petraza;
	}

	public void setPetraza(Petraza petraza) {
		this.petraza = petraza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idespecie", nullable = false)
	public Petespecie getPetespecie() {
		return this.petespecie;
	}

	public void setPetespecie(Petespecie petespecie) {
		this.petespecie = petespecie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Cotpersona getCotpersona() {
		return this.cotpersona;
	}

	public void setCotpersona(Cotpersona cotpersona) {
		this.cotpersona = cotpersona;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@Column(name = "sexo")
	public Integer getSexo() {
		return this.sexo;
	}

	public void setSexo(Integer sexo) {
		this.sexo = sexo;
	}

	@Column(name = "pesokg", precision = 5)
	public BigDecimal getPesokg() {
		return this.pesokg;
	}

	public void setPesokg(BigDecimal pesokg) {
		this.pesokg = pesokg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechanacimiento", length = 29)
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Column(name = "caracteristicas", length = 300)
	public String getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(String caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	@Column(name = "numeroidentificacion", length = 15)
	public String getNumeroidentificacion() {
		return this.numeroidentificacion;
	}

	public void setNumeroidentificacion(String numeroidentificacion) {
		this.numeroidentificacion = numeroidentificacion;
	}
	
	@Column(name = "pedigree")
	public boolean getPedigree() {
		return this.pedigree;
	}

	public void setPedigree(boolean pedigree) {
		this.pedigree = pedigree;
	}
	
	@Column(name = "microchip")
	public boolean getMicrochip() {
		return this.microchip;
	}

	public void setMicrochip(boolean microchip) {
		this.microchip = microchip;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petmascota", targetEntity = Pethistoriaclinica.class)
	public Set<Object> getPethistoriaclinicas() {
		return this.pethistoriaclinicas;
	}

	public void setPethistoriaclinicas(Set<Object> pethistoriaclinicas) {
		this.pethistoriaclinicas = pethistoriaclinicas;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petmascota", targetEntity = Petmascotacolor.class)
	public Set<Petmascotacolor> getPetmascotacolors() {
		return this.petmascotacolors;
	}

	public void setPetmascotacolors(Set<Petmascotacolor> petmascotacolors) {
		this.petmascotacolors = petmascotacolors;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petmascota", targetEntity = Cotdocumento.class)
	public Set<Object> getCotdocumentos() {
		return this.cotdocumentos;
	}

	public void setCotdocumentos(Set<Object> cotdocumentos) {
		this.cotdocumentos = cotdocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petmascota", targetEntity = Petfoto.class)
	public Set<Petfoto> getPetfotos() {
		return this.petfotos;
	}

	public void setPetfotos(Set<Petfoto> petfotos) {
		this.petfotos = petfotos;
	}
*/	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafallecimiento", length = 29)
	public Date getFechafallecimiento() {
		return this.fechafallecimiento;
	}

	public void setFechafallecimiento(Date fechafallecimiento) {
		this.fechafallecimiento = fechafallecimiento;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petmascota", targetEntity = Petcomisiondetalle.class)
	public Set<Petcomisiondetalle> getPetcomisiondetalles() {
		return this.petcomisiondetalles;
	}

	public void setPetcomisiondetalles(Set<Petcomisiondetalle> petcomisiondetalles) {
		this.petcomisiondetalles = petcomisiondetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petmascota", targetEntity = Petordenservicio.class)
	public Set<Petordenservicio> getPetordenservicios() {
		return this.petordenservicios;
	}

	public void setPetordenservicios(Set<Petordenservicio> petordenservicios) {
		this.petordenservicios = petordenservicios;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petmascota", targetEntity = Petsolicitudmortuoria.class)
	public Set<Petsolicitudmortuoria> getPetsolicitudmortuorias() {
		return this.petsolicitudmortuorias;
	}

	public void setPetsolicitudmortuorias(Set<Petsolicitudmortuoria> petsolicitudmortuorias) {
		this.petsolicitudmortuorias = petsolicitudmortuorias;
	}
*/
}
