package com.web.pet.pojo.annotations;

// Generated 29/01/2013 08:42:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PetordenserviciodetalleId generated by hbm2java
 */
@Embeddable
public class PetordenserviciodetalleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -895097552435148800L;
	private int idordenservicio;
	private int idordenserviciodetalle;

	public PetordenserviciodetalleId() {
	}

	public PetordenserviciodetalleId(int idordenservicio,
			int idordenserviciodetalle) {
		this.idordenservicio = idordenservicio;
		this.idordenserviciodetalle = idordenserviciodetalle;
	}

	@Column(name = "idordenservicio", nullable = false)
	public int getIdordenservicio() {
		return this.idordenservicio;
	}

	public void setIdordenservicio(int idordenservicio) {
		this.idordenservicio = idordenservicio;
	}

	@Column(name = "idordenserviciodetalle", nullable = false)
	public int getIdordenserviciodetalle() {
		return this.idordenserviciodetalle;
	}

	public void setIdordenserviciodetalle(int idordenserviciodetalle) {
		this.idordenserviciodetalle = idordenserviciodetalle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PetordenserviciodetalleId))
			return false;
		PetordenserviciodetalleId castOther = (PetordenserviciodetalleId) other;

		return (this.getIdordenservicio() == castOther.getIdordenservicio())
				&& (this.getIdordenserviciodetalle() == castOther
						.getIdordenserviciodetalle());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdordenservicio();
		result = 37 * result + this.getIdordenserviciodetalle();
		return result;
	}

}
