package com.web.pet.pojo.annotations;

// Generated 27/11/2016 08:02:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PetordenservicioId generated by hbm2java
 */
@Embeddable
public class PetordenservicioId implements java.io.Serializable {

	private static final long serialVersionUID = -5837892181007296229L;
	private int idordenservicio;
	private int idanio;

	public PetordenservicioId() {
	}

	public PetordenservicioId(int idordenservicio, int idanio) {
		this.idordenservicio = idordenservicio;
		this.idanio = idanio;
	}

	@Column(name = "idordenservicio", nullable = false)
	public int getIdordenservicio() {
		return this.idordenservicio;
	}

	public void setIdordenservicio(int idordenservicio) {
		this.idordenservicio = idordenservicio;
	}

	@Column(name = "idanio", nullable = false)
	public int getIdanio() {
		return this.idanio;
	}

	public void setIdanio(int idanio) {
		this.idanio = idanio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PetordenservicioId))
			return false;
		PetordenservicioId castOther = (PetordenservicioId) other;

		return (this.getIdordenservicio() == castOther.getIdordenservicio())
				&& (this.getIdanio() == castOther.getIdanio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdordenservicio();
		result = 37 * result + this.getIdanio();
		return result;
	}

}
