package com.web.pet.pojo.annotations;

// Generated 29/01/2013 08:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.web.pet.pojo.annotations.Petordenserviciodetalle;

/**
 * Petordenservicio generated by hbm2java
 */
@Entity
@Table(name = "petordenservicio", schema = "pets")
public class Petordenservicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4645223024729017391L;
	private int idordenservicio;
	private Petmascota petmascota;
	private Petestado petestado;
	private Cotlugar cotlugar;
	private Setusuario setusuario;
	private Date fechaentierro;
	private String dedicatoria;
	private String observacion;
	private Date fecharegistro;
	private String iplog;
	private Set<Petordenserviciodetalle> petordenserviciodetalles = new HashSet<Petordenserviciodetalle>(0);

	public Petordenservicio() {
	}

	public Petordenservicio(int idordenservicio, Petmascota petmascota,
			Date fecharegistro) {
		this.idordenservicio = idordenservicio;
		this.petmascota = petmascota;
		this.fecharegistro = fecharegistro;
	}

	public Petordenservicio(int idordenservicio, Petmascota petmascota,
			Petestado petestado, Cotlugar cotlugar, Setusuario setusuario,
			Date fechaentierro, String dedicatoria, String observacion,
			Date fecharegistro, String iplog, Set<Petordenserviciodetalle> petordenserviciodetalles) {
		this.idordenservicio = idordenservicio;
		this.petmascota = petmascota;
		this.petestado = petestado;
		this.cotlugar = cotlugar;
		this.setusuario = setusuario;
		this.fechaentierro = fechaentierro;
		this.dedicatoria = dedicatoria;
		this.observacion = observacion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.petordenserviciodetalles = petordenserviciodetalles;
	}

	@Id
	@Column(name = "idordenservicio", unique = true, nullable = false)
	public int getIdordenservicio() {
		return this.idordenservicio;
	}

	public void setIdordenservicio(int idordenservicio) {
		this.idordenservicio = idordenservicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmascota", nullable = false)
	public Petmascota getPetmascota() {
		return this.petmascota;
	}

	public void setPetmascota(Petmascota petmascota) {
		this.petmascota = petmascota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Petestado getPetestado() {
		return this.petestado;
	}

	public void setPetestado(Petestado petestado) {
		this.petestado = petestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlugar")
	public Cotlugar getCotlugar() {
		return this.cotlugar;
	}

	public void setCotlugar(Cotlugar cotlugar) {
		this.cotlugar = cotlugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaentierro", length = 29)
	public Date getFechaentierro() {
		return this.fechaentierro;
	}

	public void setFechaentierro(Date fechaentierro) {
		this.fechaentierro = fechaentierro;
	}

	@Column(name = "dedicatoria", length = 100)
	public String getDedicatoria() {
		return this.dedicatoria;
	}

	public void setDedicatoria(String dedicatoria) {
		this.dedicatoria = dedicatoria;
	}

	@Column(name = "observacion", length = 300)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "petordenservicio", targetEntity = Petordenserviciodetalle.class)
	public Set<Petordenserviciodetalle> getPetordenserviciodetalles() {
		return this.petordenserviciodetalles;
	}

	public void setPetordenserviciodetalles(Set<Petordenserviciodetalle> petordenserviciodetalles) {
		this.petordenserviciodetalles = petordenserviciodetalles;
	}

}
