package com.web.pet.pojo.annotations;

// Generated 29/01/2013 08:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pettablacobro generated by hbm2java
 */
@Entity
@Table(name = "pettablacobro", schema = "pets")
public class Pettablacobro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1352745549346386834L;
	private int idtablacobro;
	private Petestado petestado;
	private Setusuario setusuario;
	private BigDecimal pesodesdekg;
	private BigDecimal pesohastakg;
	private BigDecimal valor;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;

	public Pettablacobro() {
	}

	public Pettablacobro(int idtablacobro, BigDecimal pesodesdekg,
			BigDecimal pesohastakg, BigDecimal valor, Date fecharegistro) {
		this.idtablacobro = idtablacobro;
		this.pesodesdekg = pesodesdekg;
		this.pesohastakg = pesohastakg;
		this.valor = valor;
		this.fecharegistro = fecharegistro;
	}

	public Pettablacobro(int idtablacobro, Petestado petestado,
			Setusuario setusuario, BigDecimal pesodesdekg,
			BigDecimal pesohastakg, BigDecimal valor, String descripcion,
			Date fecharegistro, String iplog) {
		this.idtablacobro = idtablacobro;
		this.petestado = petestado;
		this.setusuario = setusuario;
		this.pesodesdekg = pesodesdekg;
		this.pesohastakg = pesohastakg;
		this.valor = valor;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idtablacobro", unique = true, nullable = false)
	public int getIdtablacobro() {
		return this.idtablacobro;
	}

	public void setIdtablacobro(int idtablacobro) {
		this.idtablacobro = idtablacobro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Petestado getPetestado() {
		return this.petestado;
	}

	public void setPetestado(Petestado petestado) {
		this.petestado = petestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "pesodesdekg", nullable = false, precision = 5)
	public BigDecimal getPesodesdekg() {
		return this.pesodesdekg;
	}

	public void setPesodesdekg(BigDecimal pesodesdekg) {
		this.pesodesdekg = pesodesdekg;
	}

	@Column(name = "pesohastakg", nullable = false, precision = 5)
	public BigDecimal getPesohastakg() {
		return this.pesohastakg;
	}

	public void setPesohastakg(BigDecimal pesohastakg) {
		this.pesohastakg = pesohastakg;
	}

	@Column(name = "valor", nullable = false, precision = 5)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
