package com.web.pet.pojo.annotations;

// Generated 29/01/2013 08:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pettipocomision generated by hbm2java
 */
@Entity
@Table(name = "pettipocomision")
public class Pettipocomision implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6044095616236288268L;
	private int idtipocomision;
	private Petestado petestado;
	private Setusuario setusuario;
	private String nombre;
	private String descripcion;
	private BigDecimal porcentaje;
	private Date fecharegistro;
	private String iplog;

	public Pettipocomision() {
	}

	public Pettipocomision(int idtipocomision, String nombre, Date fecharegistro) {
		this.idtipocomision = idtipocomision;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
	}

	public Pettipocomision(int idtipocomision, Petestado petestado,
			Setusuario setusuario, String nombre, String descripcion,
			BigDecimal porcentaje, Date fecharegistro, String iplog) {
		this.idtipocomision = idtipocomision;
		this.petestado = petestado;
		this.setusuario = setusuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.porcentaje = porcentaje;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
	}

	@Id
	@Column(name = "idtipocomision", unique = true, nullable = false)
	public int getIdtipocomision() {
		return this.idtipocomision;
	}

	public void setIdtipocomision(int idtipocomision) {
		this.idtipocomision = idtipocomision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Petestado getPetestado() {
		return this.petestado;
	}

	public void setPetestado(Petestado petestado) {
		this.petestado = petestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Setusuario getSetusuario() {
		return this.setusuario;
	}

	public void setSetusuario(Setusuario setusuario) {
		this.setusuario = setusuario;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "porcentaje", precision = 5)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

}
