package com.web.pet.pojo.annotations;

// Generated 26/07/2012 03:22:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Setusuario generated by hbm2java
 */
@Entity
@Table(name = "setusuario")
public class Setusuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4853432224835132249L;
	private int idusuario;
	private Setestado setestado;
	private Setperfil setperfil;
	private Cotpersona cotpersona;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
	private String clave;
	private Date fechamodificacion;

	public Setusuario() {
	}

	public Setusuario(int idusuario, Date fecharegistro) {
		this.idusuario = idusuario;
		this.fecharegistro = fecharegistro;
	}

	public Setusuario(int idusuario, Setestado setestado, Setperfil setperfil,
			Cotpersona cotpersona, String nombre, String descripcion,
			Date fecharegistro, String iplog, String clave, Date fechamodificacion) {
		this.idusuario = idusuario;
		this.setestado = setestado;
		this.setperfil = setperfil;
		this.cotpersona = cotpersona;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.clave = clave;
		this.fechamodificacion = fechamodificacion;
	}

	@Id
	@Column(name = "idusuario", unique = true, nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idperfil")
	public Setperfil getSetperfil() {
		return this.setperfil;
	}

	public void setSetperfil(Setperfil setperfil) {
		this.setperfil = setperfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona")
	public Cotpersona getCotpersona() {
		return this.cotpersona;
	}

	public void setCotpersona(Cotpersona cotpersona) {
		this.cotpersona = cotpersona;
	}

	@Column(name = "nombre", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@Column(name = "clave", length = 100)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamodificacion",  length = 29)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}
	
}
