package com.web.pet.pojo.annotations;

// Generated 26/07/2012 03:22:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Setusuario generated by hbm2java
 */
@Entity
@Table(name = "setusuario", schema = "seguridad")
public class Setusuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4853432224835132249L;
	private int idusuario;
	private Setestado setestado;
	private Setperfil setperfil;
	private Cotpersona cotpersona;
	private String nombre;
	private String descripcion;
	private Date fecharegistro;
	private String iplog;
	private String clave;
//	private Set<Cotservicio> cotservicios = new HashSet<Cotservicio>(0);
//	private Set<Cottiposervicio> cottiposervicios = new HashSet<Cottiposervicio>(0);
//	private Set<Pettablacobro> pettablacobros = new HashSet<Pettablacobro>(0);
//	private Set<Cotlugar> cotlugars = new HashSet<Cotlugar>(0);
//	private Set<Petcomision> petcomisions = new HashSet<Petcomision>(0);
//	private Set<Petordenservicio> petordenservicios = new HashSet<Petordenservicio>(0);
//	private Set<Pettipocomision> pettipocomisions = new HashSet<Pettipocomision>(0);
//	private Set<Petordenserviciodetalle> petordenserviciodetalles = new HashSet<Petordenserviciodetalle>(0);
//	private Set<Pethistoriaclinicadetalle> pethistoriaclinicadetalles = new HashSet<Pethistoriaclinicadetalle>(0);
//	private Set<Cotevento> coteventos = new HashSet<Cotevento>(0);
//	private Set<Petvacunamascota> petvacunamascotas = new HashSet<Petvacunamascota>(0);
//	private Set<Petmascotacolor> petmascotacolors = new HashSet<Petmascotacolor>(0);
//	private Set<Setestado> setestados = new HashSet<Setestado>(0);
//	private Set<Setperfil> setperfils = new HashSet<Setperfil>(0);
//	private Set<Cotestado> cotestados = new HashSet<Cotestado>(0);
//	private Set<Petestado> petestados = new HashSet<Petestado>(0);
//	private Set<Pethistoriaclinica> pethistoriaclinicas = new HashSet<Pethistoriaclinica>(0);
//	private Set<Petfoto> petfotos = new HashSet<Petfoto>(0);
//	private Set<Cottipovacuna> cottipovacunas = new HashSet<Cottipovacuna>(0);
//	private Set<Cotgrupodocumento> cotgrupodocumentos = new HashSet<Cotgrupodocumento>(0);
//	private Set<Cotcolor> cotcolors = new HashSet<Cotcolor>(0);
//	private Set<Cotpersona> cotpersonas = new HashSet<Cotpersona>(0);
//	private Set<Setmenu> setmenus = new HashSet<Setmenu>(0);
//	private Set<Cottipodocumento> cottipodocumentos = new HashSet<Cottipodocumento>(0);
//	private Set<Petraza> petrazas = new HashSet<Petraza>(0);
//	private Set<Petespecie> petespecies = new HashSet<Petespecie>(0);
//	private Set<Cotdocumento> cotdocumentos = new HashSet<Cotdocumento>(0);
//	private Set<Cottipoidentificacion> cottipoidentificacions = new HashSet<Cottipoidentificacion>(0);
//	private Set<Petmascota> petmascotas = new HashSet<Petmascota>(0);
//	private Set<Cotperiodotiempo> cotperiodotiempos = new HashSet<Cotperiodotiempo>(0);
//	private Set<Pettipoexamen> pettipoexamens = new HashSet<Pettipoexamen>(0);
//	private Set<Petexamen> petexamens = new HashSet<Petexamen>(0);
//	private Set<Petplantillavacuna> petplantillavacunas = new HashSet<Petplantillavacuna>(0);

	public Setusuario() {
	}

	public Setusuario(int idusuario, Date fecharegistro) {
		this.idusuario = idusuario;
		this.fecharegistro = fecharegistro;
	}

	public Setusuario(int idusuario, Setestado setestado, Setperfil setperfil,
			Cotpersona cotpersona, String nombre, String descripcion,
			Date fecharegistro, String iplog, String clave/*,
			Set<Cotservicio> cotservicios, Set<Cottiposervicio> cottiposervicios,
			Set<Pettablacobro> pettablacobros, Set<Cotlugar> cotlugars, Set<Petcomision> petcomisions, 
			Set<Petordenservicio> petordenservicios, Set<Pettipocomision> pettipocomisions, Set<Petordenserviciodetalle> petordenserviciodetalles,
			Set<Pethistoriaclinicadetalle> pethistoriaclinicadetalles, Set<Cotevento> coteventos,
			Set<Petvacunamascota> petvacunamascotas, Set<Petmascotacolor> petmascotacolors, Set<Setestado> setestados,
			Set<Setperfil> setperfils, Set<Cotestado> cotestados, Set<Petestado> petestados,
			Set<Pethistoriaclinica> pethistoriaclinicas, Set<Petfoto> petfotos, Set<Cottipovacuna> cottipovacunas,
			Set<Cotgrupodocumento> cotgrupodocumentos, Set<Cotcolor> cotcolors, Set<Cotpersona> cotpersonas,
			Set<Setmenu> setmenus, Set<Cottipodocumento> cottipodocumentos, Set<Petraza> petrazas, Set<Petespecie> petespecies,
			Set<Cotdocumento> cotdocumentos, Set<Cottipoidentificacion> cottipoidentificacions, Set<Petmascota> petmascotas,
			Set<Cotperiodotiempo> cotperiodotiempos, Set<Pettipoexamen> pettipoexamens, Set<Petexamen> petexamens, Set<Petplantillavacuna> petplantillavacunas*/) {
		this.idusuario = idusuario;
		this.setestado = setestado;
		this.setperfil = setperfil;
		this.cotpersona = cotpersona;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.clave = clave;
//		this.cotservicios = cotservicios;
//		this.cottiposervicios = cottiposervicios;
//		this.pettablacobros = pettablacobros;
//		this.cotlugars = cotlugars;
//		this.petcomisions = petcomisions;
//		this.petordenservicios = petordenservicios;
//		this.pettipocomisions = pettipocomisions;
//		this.petordenserviciodetalles = petordenserviciodetalles;
//		this.pethistoriaclinicadetalles = pethistoriaclinicadetalles;
//		this.coteventos = coteventos;
//		this.petvacunamascotas = petvacunamascotas;
//		this.petmascotacolors = petmascotacolors;
//		this.setestados = setestados;
//		this.setperfils = setperfils;
//		this.cotestados = cotestados;
//		this.petestados = petestados;
//		this.pethistoriaclinicas = pethistoriaclinicas;
//		this.petfotos = petfotos;
//		this.cottipovacunas = cottipovacunas;
//		this.cotgrupodocumentos = cotgrupodocumentos;
//		this.cotcolors = cotcolors;
//		this.cotpersonas = cotpersonas;
//		this.setmenus = setmenus;
//		this.cottipodocumentos = cottipodocumentos;
//		this.petrazas = petrazas;
//		this.petespecies = petespecies;
//		this.cotdocumentos = cotdocumentos;
//		this.cottipoidentificacions = cottipoidentificacions;
//		this.petmascotas = petmascotas;
//		this.cotperiodotiempos = cotperiodotiempos;
//		this.pettipoexamens = pettipoexamens;
//		this.petexamens = petexamens;
//		this.petplantillavacunas = petplantillavacunas;
	}

	@Id
	@Column(name = "idusuario", unique = true, nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idperfil")
	public Setperfil getSetperfil() {
		return this.setperfil;
	}

	public void setSetperfil(Setperfil setperfil) {
		this.setperfil = setperfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona")
	public Cotpersona getCotpersona() {
		return this.cotpersona;
	}

	public void setCotpersona(Cotpersona cotpersona) {
		this.cotpersona = cotpersona;
	}

	@Column(name = "nombre", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecharegistro", nullable = false, length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}

	@Column(name = "clave", length = 30)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}
/*	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotservicio.class)
	public Set<Cotservicio> getCotservicios() {
		return this.cotservicios;
	}

	public void setCotservicios(Set<Cotservicio> cotservicios) {
		this.cotservicios = cotservicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cottiposervicio.class)
	public Set<Cottiposervicio> getCottiposervicios() {
		return this.cottiposervicios;
	}

	public void setCottiposervicios(Set<Cottiposervicio> cottiposervicios) {
		this.cottiposervicios = cottiposervicios;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Pettablacobro.class)
	public Set<Pettablacobro> getPettablacobros() {
		return this.pettablacobros;
	}

	public void setPettablacobros(Set<Pettablacobro> pettablacobros) {
		this.pettablacobros = pettablacobros;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotlugar.class)
	public Set<Cotlugar> getCotlugars() {
		return this.cotlugars;
	}

	public void setCotlugars(Set<Cotlugar> cotlugars) {
		this.cotlugars = cotlugars;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petcomision.class)
	public Set<Petcomision> getPetcomisions() {
		return this.petcomisions;
	}

	public void setPetcomisions(Set<Petcomision> petcomisions) {
		this.petcomisions = petcomisions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petordenservicio.class)
	public Set<Petordenservicio> getPetordenservicios() {
		return this.petordenservicios;
	}

	public void setPetordenservicios(Set<Petordenservicio> petordenservicios) {
		this.petordenservicios = petordenservicios;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Pettipocomision.class)
	public Set<Pettipocomision> getPettipocomisions() {
		return this.pettipocomisions;
	}

	public void setPettipocomisions(Set<Pettipocomision> pettipocomisions) {
		this.pettipocomisions = pettipocomisions;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petordenserviciodetalle.class)
	public Set<Petordenserviciodetalle> getPetordenserviciodetalles() {
		return this.petordenserviciodetalles;
	}

	public void setPetordenserviciodetalles(Set<Petordenserviciodetalle> petordenserviciodetalles) {
		this.petordenserviciodetalles = petordenserviciodetalles;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Pethistoriaclinicadetalle.class)
	public Set<Pethistoriaclinicadetalle> getPethistoriaclinicadetalles() {
		return this.pethistoriaclinicadetalles;
	}

	public void setPethistoriaclinicadetalles(Set<Pethistoriaclinicadetalle> pethistoriaclinicadetalles) {
		this.pethistoriaclinicadetalles = pethistoriaclinicadetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotevento.class)
	public Set<Cotevento> getCoteventos() {
		return this.coteventos;
	}

	public void setCoteventos(Set<Cotevento> coteventos) {
		this.coteventos = coteventos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petvacunamascota.class)
	public Set<Petvacunamascota> getPetvacunamascotas() {
		return this.petvacunamascotas;
	}

	public void setPetvacunamascotas(Set<Petvacunamascota> petvacunamascotas) {
		this.petvacunamascotas = petvacunamascotas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petmascotacolor.class)
	public Set<Petmascotacolor> getPetmascotacolors() {
		return this.petmascotacolors;
	}

	public void setPetmascotacolors(Set<Petmascotacolor> petmascotacolors) {
		this.petmascotacolors = petmascotacolors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Setestado.class)
	public Set<Setestado> getSetestados() {
		return this.setestados;
	}

	public void setSetestados(Set<Setestado> setestados) {
		this.setestados = setestados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Setperfil.class)
	public Set<Setperfil> getSetperfils() {
		return this.setperfils;
	}

	public void setSetperfils(Set<Setperfil> setperfils) {
		this.setperfils = setperfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotestado.class)
	public Set<Cotestado> getCotestados() {
		return this.cotestados;
	}

	public void setCotestados(Set<Cotestado> cotestados) {
		this.cotestados = cotestados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petestado.class)
	public Set<Petestado> getPetestados() {
		return this.petestados;
	}

	public void setPetestados(Set<Petestado> petestados) {
		this.petestados = petestados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Pethistoriaclinica.class)
	public Set<Pethistoriaclinica> getPethistoriaclinicas() {
		return this.pethistoriaclinicas;
	}

	public void setPethistoriaclinicas(Set<Pethistoriaclinica> pethistoriaclinicas) {
		this.pethistoriaclinicas = pethistoriaclinicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petfoto.class)
	public Set<Petfoto> getPetfotos() {
		return this.petfotos;
	}

	public void setPetfotos(Set<Petfoto> petfotos) {
		this.petfotos = petfotos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cottipovacuna.class)
	public Set<Cottipovacuna> getCottipovacunas() {
		return this.cottipovacunas;
	}

	public void setCottipovacunas(Set<Cottipovacuna> cottipovacunas) {
		this.cottipovacunas = cottipovacunas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotgrupodocumento.class)
	public Set<Cotgrupodocumento> getCotgrupodocumentos() {
		return this.cotgrupodocumentos;
	}

	public void setCotgrupodocumentos(Set<Cotgrupodocumento> cotgrupodocumentos) {
		this.cotgrupodocumentos = cotgrupodocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotcolor.class)
	public Set<Cotcolor> getCotcolors() {
		return this.cotcolors;
	}

	public void setCotcolors(Set<Cotcolor> cotcolors) {
		this.cotcolors = cotcolors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotpersona.class)
	public Set<Cotpersona> getCotpersonas() {
		return this.cotpersonas;
	}

	public void setCotpersonas(Set<Cotpersona> cotpersonas) {
		this.cotpersonas = cotpersonas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Setmenu.class)
	public Set<Setmenu> getSetmenus() {
		return this.setmenus;
	}

	public void setSetmenus(Set<Setmenu> setmenus) {
		this.setmenus = setmenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cottipodocumento.class)
	public Set<Cottipodocumento> getCottipodocumentos() {
		return this.cottipodocumentos;
	}

	public void setCottipodocumentos(Set<Cottipodocumento> cottipodocumentos) {
		this.cottipodocumentos = cottipodocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petraza.class)
	public Set<Petraza> getPetrazas() {
		return this.petrazas;
	}

	public void setPetrazas(Set<Petraza> petrazas) {
		this.petrazas = petrazas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petespecie.class)
	public Set<Petespecie> getPetespecies() {
		return this.petespecies;
	}

	public void setPetespecies(Set<Petespecie> petespecies) {
		this.petespecies = petespecies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotdocumento.class)
	public Set<Cotdocumento> getCotdocumentos() {
		return this.cotdocumentos;
	}

	public void setCotdocumentos(Set<Cotdocumento> cotdocumentos) {
		this.cotdocumentos = cotdocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cottipoidentificacion.class)
	public Set<Cottipoidentificacion> getCottipoidentificacions() {
		return this.cottipoidentificacions;
	}

	public void setCottipoidentificacions(Set<Cottipoidentificacion> cottipoidentificacions) {
		this.cottipoidentificacions = cottipoidentificacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petmascota.class)
	public Set<Petmascota> getPetmascotas() {
		return this.petmascotas;
	}

	public void setPetmascotas(Set<Petmascota> petmascotas) {
		this.petmascotas = petmascotas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Cotperiodotiempo.class)
	public Set<Cotperiodotiempo> getCotperiodotiempos() {
		return this.cotperiodotiempos;
	}

	public void setCotperiodotiempos(Set<Cotperiodotiempo> cotperiodotiempos) {
		this.cotperiodotiempos = cotperiodotiempos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Pettipoexamen.class)
	public Set<Pettipoexamen> getPettipoexamens() {
		return this.pettipoexamens;
	}

	public void setPettipoexamens(Set<Pettipoexamen> pettipoexamens) {
		this.pettipoexamens = pettipoexamens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petexamen.class)
	public Set<Petexamen> getPetexamens() {
		return this.petexamens;
	}

	public void setPetexamens(Set<Petexamen> petexamens) {
		this.petexamens = petexamens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setusuario", targetEntity = Petplantillavacuna.class)
	public Set<Petplantillavacuna> getPetplantillavacunas() {
		return this.petplantillavacunas;
	}

	public void setPetplantillavacunas(Set<Petplantillavacuna> petplantillavacunas) {
		this.petplantillavacunas = petplantillavacunas;
	}
*/
}
