package com.web.pet.pojo.annotations;


// Generated 14/01/2011 02:41:52 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sevmenu generated by hbm2java
 */
@Entity
@Table(name = "setmenu")
public class Sevmenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7284646734458211779L;
	private Integer idmenu;
	private String nombre;
	private String descripcion;
	private Integer idmenupadre;
	private Integer nivel;
	private String iconourl;
	private String paginaurl;
	private Integer orden;
	private Date fecharegistro;
	private String iplog;
	private Setestado setestado;

	public Sevmenu() {
	}

	public Sevmenu(Integer idmenu, String nombre, String descripcion,
			Integer idmenupadre, Integer nivel, String iconourl,
			String paginaurl, Integer orden, Date fecharegistro, String iplog, 
			Setestado setestado) {
		this.idmenu = idmenu;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.idmenupadre = idmenupadre;
		this.nivel = nivel;
		this.iconourl = iconourl;
		this.paginaurl = paginaurl;
		this.orden = orden;
		this.fecharegistro = fecharegistro;
		this.iplog = iplog;
		this.setestado = setestado;
	}
	
	@Id
	@Column(name = "idmenu")
	public Integer getIdmenu() {
		return this.idmenu;
	}

	public void setIdmenu(Integer idmenu) {
		this.idmenu = idmenu;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "idmenupadre")
	public Integer getIdmenupadre() {
		return this.idmenupadre;
	}

	public void setIdmenupadre(Integer idmenupadre) {
		this.idmenupadre = idmenupadre;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "iconourl", length = 100)
	public String getIconourl() {
		return this.iconourl;
	}

	public void setIconourl(String iconourl) {
		this.iconourl = iconourl;
	}

	@Column(name = "paginaurl", length = 200)
	public String getPaginaurl() {
		return this.paginaurl;
	}

	public void setPaginaurl(String paginaurl) {
		this.paginaurl = paginaurl;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "fecharegistro", length = 29)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "iplog", length = 20)
	public String getIplog() {
		return this.iplog;
	}

	public void setIplog(String iplog) {
		this.iplog = iplog;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado")
	public Setestado getSetestado() {
		return this.setestado;
	}

	public void setSetestado(Setestado setestado) {
		this.setestado = setestado;
	}

}
